### ISSUE TITLE
branding logo detail?

### ISSUE THREAD

**Issue by veenone** [mahendrapaipuri/grafana-dashboard-reporter-app#36]
Hi @mahendrapaipuri ,

I wanted to know for the current implementation, what is the recommended dimension for the branding logo?
I tried to put a png with 478x120 but it looks wrapped in the pdf.

**Comment by mahendrapaipuri** [comment]
Currently it is [hard coded to have a sqaurish aspect ratio](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/blob/6231f7cea82dd292235ff1e73ea30674ba4cd5cd/pkg/plugin/templates/footer.gohtml#L30). But I think it makes more sense to only fix the height so that width will be automatically set based on the aspect ratio of the logo

**Comment by mahendrapaipuri** [comment]
@veenone Actually there was a bug in including logo in the report. I fixed it and cut a [new release](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/releases/tag/v1.4.1). Please test it out.

**Comment by veenone** [comment]
@mahendrapaipuri , I will try it later. But can you inform us what is the reference logo size (in pixels) to attain the proper sizing?

**Comment by mahendrapaipuri** [comment]
It is 25px in height. With the new release, it should scale the logo automatically to proper size keeping the aspect ratio intact!
